[package]
name = "youtube-downloader-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12.0", features = ["macros"] }
tokio = { version = "1.0", features = ["full"] }
rand = "0.8.5"